[package]
name = "telemetry"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0.210", features = ["derive"] }
serde-big-array = { version = "0.5.1" }
bincode = { version = "1.3.3" }
